USE TDC_DW;
GO

CREATE OR ALTER PROCEDURE SP_LOAD_DIM_RUBRO
AS
BEGIN
	DELETE FROM DIM_RUBRO;
	DBCC CHECKIDENT ('DIM_RUBRO', RESEED, 0);
		
	INSERT INTO DIM_RUBRO (nombre_rubro)
	SELECT DISTINCT 
		CASE
			WHEN DETAIL LIKE '%Beer%'		THEN 'Beer'
			WHEN DETAIL LIKE '%Cola%'		THEN 'Cola'
			WHEN DETAIL LIKE '%Soda%'		THEN 'Soda'
			WHEN DETAIL LIKE '%Juice%'		THEN 'Juice'
			WHEN DETAIL LIKE '%Energy drink%'		THEN 'Energy drink'
			ELSE 'Desconocido'
		END
	FROM STG_TDC.dbo.STG_PRODUCTS
END;
GO



